// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccResourceFvEpMacTagWithFvTenant(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigFvEpMacTagMinDependencyWithFvTenant,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "bd_name", "test_bd_name"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "mac", "00:00:00:00:00:01"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "id_attribute", "0"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "name", ""),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "name_alias", ""),
				),
			},
			// Update with all config and verify default APIC values
			{
				Config:             testConfigFvEpMacTagAllDependencyWithFvTenant,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "bd_name", "test_bd_name"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "mac", "00:00:00:00:00:01"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "annotation", "annotation"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "id_attribute", "1"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "name", "name"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "name_alias", "name_alias"),
				),
			},
			// Update with minimum config and verify config is unchanged
			{
				Config:             testConfigFvEpMacTagMinDependencyWithFvTenant,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "bd_name", "test_bd_name"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "mac", "00:00:00:00:00:01"),
				),
			},
			// Update with empty strings config or default value
			{
				Config:             testConfigFvEpMacTagResetDependencyWithFvTenant,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "bd_name", "test_bd_name"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "mac", "00:00:00:00:00:01"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "id_attribute", "0"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "name", ""),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "name_alias", ""),
				),
			},
			// Import testing
			{
				ResourceName:      "aci_endpoint_tag_mac.test",
				ImportState:       true,
				ImportStateVerify: true,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "bd_name", "test_bd_name"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "mac", "00:00:00:00:00:01"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "id_attribute", "0"),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "name", ""),
					resource.TestCheckResourceAttr("aci_endpoint_tag_mac.test", "name_alias", ""),
				),
			},
		},
	})
}

const testConfigFvEpMacTagMinDependencyWithFvTenant = testConfigFvTenantMin + `
resource "aci_endpoint_tag_mac" "test" {
  parent_dn = aci_tenant.test.id
  bd_name = "test_bd_name"
  mac = "00:00:00:00:00:01"
}
`

const testConfigFvEpMacTagAllDependencyWithFvTenant = testConfigFvTenantMin + `
resource "aci_endpoint_tag_mac" "test" {
  parent_dn = aci_tenant.test.id
  bd_name = "test_bd_name"
  mac = "00:00:00:00:00:01"
  annotation = "annotation"
  id_attribute = "1"
  name = "name"
  name_alias = "name_alias"
}
`

const testConfigFvEpMacTagResetDependencyWithFvTenant = testConfigFvTenantMin + `
resource "aci_endpoint_tag_mac" "test" {
  parent_dn = aci_tenant.test.id
  bd_name = "test_bd_name"
  mac = "00:00:00:00:00:01"
  annotation = "orchestrator:terraform"
  id_attribute = "0"
  name = ""
  name_alias = ""
}
`
