// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"reflect"
	"strings"

	"github.com/ciscoecosystem/aci-go-client/v2/client"
	"github.com/ciscoecosystem/aci-go-client/v2/container"
	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &CommPolResource{}
var _ resource.ResourceWithImportState = &CommPolResource{}

func NewCommPolResource() resource.Resource {
	return &CommPolResource{}
}

// CommPolResource defines the resource implementation.
type CommPolResource struct {
	client *client.Client
}

// CommPolResourceModel describes the resource data model.
type CommPolResourceModel struct {
	Id                            types.String `tfsdk:"id"`
	Annotation                    types.String `tfsdk:"annotation"`
	Descr                         types.String `tfsdk:"description"`
	Name                          types.String `tfsdk:"name"`
	NameAlias                     types.String `tfsdk:"name_alias"`
	OwnerKey                      types.String `tfsdk:"owner_key"`
	OwnerTag                      types.String `tfsdk:"owner_tag"`
	StrictSecurityOnApicOOBSubnet types.String `tfsdk:"strict_security_on_apic_oob_subnet"`
	CommHttps                     types.Set    `tfsdk:"http_ssl_configuration"`
	TagAnnotation                 types.Set    `tfsdk:"annotations"`
	TagTag                        types.Set    `tfsdk:"tags"`
}

// CommHttpsCommPolResourceModel describes the resource data model for the children without relation ships.
type CommHttpsCommPolResourceModel struct {
	AccessControlAllowCredential types.String `tfsdk:"access_control_allow_credential"`
	AccessControlAllowOrigins    types.String `tfsdk:"access_control_allow_origins"`
	AdminSt                      types.String `tfsdk:"admin_st"`
	Annotation                   types.String `tfsdk:"annotation"`
	CliOnlyMode                  types.String `tfsdk:"cli_only_mode"`
	ClientCertAuthState          types.String `tfsdk:"client_cert_auth_state"`
	Descr                        types.String `tfsdk:"description"`
	DhParam                      types.String `tfsdk:"dh_param"`
	GlobalThrottleRate           types.String `tfsdk:"global_throttle_rate"`
	GlobalThrottleSt             types.String `tfsdk:"global_throttle_st"`
	GlobalThrottleUnit           types.String `tfsdk:"global_throttle_unit"`
	MaxRequestStatusCount        types.String `tfsdk:"max_request_status_count"`
	Name                         types.String `tfsdk:"name"`
	NameAlias                    types.String `tfsdk:"name_alias"`
	NodeExporter                 types.String `tfsdk:"node_exporter"`
	Port                         types.String `tfsdk:"port"`
	Referer                      types.String `tfsdk:"referer"`
	ServerHeader                 types.String `tfsdk:"server_header"`
	SslProtocols                 types.Set    `tfsdk:"ssl_protocols"`
	ThrottleRate                 types.String `tfsdk:"throttle_rate"`
	ThrottleSt                   types.String `tfsdk:"throttle_st"`
	VisoreAccess                 types.String `tfsdk:"visore_access"`
	CommRsClientCertCA           types.Set    `tfsdk:"tp"`
	CommRsKeyRing                types.Set    `tfsdk:"key_ring"`
	TagAnnotation                types.Set    `tfsdk:"annotations"`
	TagTag                       types.Set    `tfsdk:"tags"`
}

func CommHttpsCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"access_control_allow_credential": types.StringType,
		"access_control_allow_origins":    types.StringType,
		"admin_st":                        types.StringType,
		"annotation":                      types.StringType,
		"cli_only_mode":                   types.StringType,
		"client_cert_auth_state":          types.StringType,
		"description":                     types.StringType,
		"dh_param":                        types.StringType,
		"global_throttle_rate":            types.StringType,
		"global_throttle_st":              types.StringType,
		"global_throttle_unit":            types.StringType,
		"max_request_status_count":        types.StringType,
		"name":                            types.StringType,
		"name_alias":                      types.StringType,
		"node_exporter":                   types.StringType,
		"port":                            types.StringType,
		"referer":                         types.StringType,
		"server_header":                   types.StringType,
		"ssl_protocols":                   types.SetType{ElemType: types.StringType},
		"throttle_rate":                   types.StringType,
		"throttle_st":                     types.StringType,
		"visore_access":                   types.StringType,
		"tp":                              types.SetType{ElemType: types.StringType},
		"key_ring":                        types.SetType{ElemType: types.StringType},
		"annotations":                     types.SetType{ElemType: types.StringType},
		"tags":                            types.SetType{ElemType: types.StringType},
	}
}

func CommHttpsCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, CommHttpsCommPolResourceModelAttributeTypes())
}

// CommRsClientCertCACommHttpsCommPolResourceModel describes the resource data model for the children without relation ships.
type CommRsClientCertCACommHttpsCommPolResourceModel struct {
	Annotation    types.String `tfsdk:"annotation"`
	TDn           types.String `tfsdk:"target_dn"`
	TagAnnotation types.Set    `tfsdk:"annotations"`
	TagTag        types.Set    `tfsdk:"tags"`
}

func CommRsClientCertCACommHttpsCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"annotation":  types.StringType,
		"target_dn":   types.StringType,
		"annotations": types.SetType{ElemType: types.StringType},
		"tags":        types.SetType{ElemType: types.StringType},
	}
}

func CommRsClientCertCACommHttpsCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, CommRsClientCertCACommHttpsCommPolResourceModelAttributeTypes())
}

// TagAnnotationCommRsClientCertCACommHttpsCommPolResourceModel describes the resource data model for the children without relation ships.
type TagAnnotationCommRsClientCertCACommHttpsCommPolResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func TagAnnotationCommRsClientCertCACommHttpsCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	}
}

func TagAnnotationCommRsClientCertCACommHttpsCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, TagAnnotationCommRsClientCertCACommHttpsCommPolResourceModelAttributeTypes())
}

// TagTagCommRsClientCertCACommHttpsCommPolResourceModel describes the resource data model for the children without relation ships.
type TagTagCommRsClientCertCACommHttpsCommPolResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func TagTagCommRsClientCertCACommHttpsCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	}
}

func TagTagCommRsClientCertCACommHttpsCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, TagTagCommRsClientCertCACommHttpsCommPolResourceModelAttributeTypes())
}

// CommRsKeyRingCommHttpsCommPolResourceModel describes the resource data model for the children without relation ships.
type CommRsKeyRingCommHttpsCommPolResourceModel struct {
	Annotation       types.String `tfsdk:"annotation"`
	TnPkiKeyRingName types.String `tfsdk:"tn_pki_key_ring_name"`
	TagAnnotation    types.Set    `tfsdk:"annotations"`
	TagTag           types.Set    `tfsdk:"tags"`
}

func CommRsKeyRingCommHttpsCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"annotation":           types.StringType,
		"tn_pki_key_ring_name": types.StringType,
		"annotations":          types.SetType{ElemType: types.StringType},
		"tags":                 types.SetType{ElemType: types.StringType},
	}
}

func CommRsKeyRingCommHttpsCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, CommRsKeyRingCommHttpsCommPolResourceModelAttributeTypes())
}

// TagAnnotationCommRsKeyRingCommHttpsCommPolResourceModel describes the resource data model for the children without relation ships.
type TagAnnotationCommRsKeyRingCommHttpsCommPolResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func TagAnnotationCommRsKeyRingCommHttpsCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	}
}

func TagAnnotationCommRsKeyRingCommHttpsCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, TagAnnotationCommRsKeyRingCommHttpsCommPolResourceModelAttributeTypes())
}

// TagTagCommRsKeyRingCommHttpsCommPolResourceModel describes the resource data model for the children without relation ships.
type TagTagCommRsKeyRingCommHttpsCommPolResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func TagTagCommRsKeyRingCommHttpsCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	}
}

func TagTagCommRsKeyRingCommHttpsCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, TagTagCommRsKeyRingCommHttpsCommPolResourceModelAttributeTypes())
}

// TagAnnotationCommHttpsCommPolResourceModel describes the resource data model for the children without relation ships.
type TagAnnotationCommHttpsCommPolResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func TagAnnotationCommHttpsCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	}
}

func TagAnnotationCommHttpsCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, TagAnnotationCommHttpsCommPolResourceModelAttributeTypes())
}

// TagTagCommHttpsCommPolResourceModel describes the resource data model for the children without relation ships.
type TagTagCommHttpsCommPolResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func TagTagCommHttpsCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	}
}

func TagTagCommHttpsCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, TagTagCommHttpsCommPolResourceModelAttributeTypes())
}

// TagAnnotationCommPolResourceModel describes the resource data model for the children without relation ships.
type TagAnnotationCommPolResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func TagAnnotationCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	}
}

func TagAnnotationCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, TagAnnotationCommPolResourceModelAttributeTypes())
}

// TagTagCommPolResourceModel describes the resource data model for the children without relation ships.
type TagTagCommPolResourceModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

func TagTagCommPolResourceModelAttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"key":   types.StringType,
		"value": types.StringType,
	}
}

func TagTagCommPolResourceModelElementType() attr.TypeWithAttributeTypes {
	return basetypes.ObjectType.WithAttributeTypes(basetypes.ObjectType{}, TagTagCommPolResourceModelAttributeTypes())
}

type CommPolIdentifier struct {
	Name types.String
}

func (r *CommPolResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	tflog.Debug(ctx, "Start metadata of resource: aci_communication_policy")
	resp.TypeName = req.ProviderTypeName + "_communication_policy"
	tflog.Debug(ctx, "End metadata of resource: aci_communication_policy")
}

func (r *CommPolResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	tflog.Debug(ctx, "Start schema of resource: aci_communication_policy")
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "The communication_policy resource for the 'commPol' class",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The distinguished name (DN) of the Communication Policy object.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"annotation": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				Default:             stringdefault.StaticString(globalAnnotation),
				MarkdownDescription: `The annotation of the Communication Policy object.`,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				MarkdownDescription: `The description of the Communication Policy object.`,
			},
			"name": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
					stringplanmodifier.RequiresReplace(),
				},
				MarkdownDescription: `The name of the Communication Policy object.`,
			},
			"name_alias": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				MarkdownDescription: `The name alias of the Communication Policy object.`,
			},
			"owner_key": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				MarkdownDescription: `The key for enabling clients to own their data for entity correlation.`,
			},
			"owner_tag": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				MarkdownDescription: `A tag for enabling clients to add their own data. For example, to indicate who created this object.`,
			},
			"strict_security_on_apic_oob_subnet": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("no", "yes"),
				},
				MarkdownDescription: `remove implicit access on apic oob from any apic OOB subnet IP.`,
			},
			"http_ssl_configuration": schema.SetNestedAttribute{
				MarkdownDescription: `HTTPS`,
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.Set{
					setvalidator.SizeAtMost(1),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"access_control_allow_credential": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							Validators: []validator.String{
								stringvalidator.OneOf("disabled", "enabled"),
							},
							MarkdownDescription: `accessControlAllowCredential.`,
						},
						"access_control_allow_origins": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: ``,
						},
						"admin_st": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							Validators: []validator.String{
								stringvalidator.OneOf("disabled", "enabled"),
							},
							MarkdownDescription: `The state of HTTPS communication service. This can be enabled or disabled.`,
						},
						"annotation": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The annotation of the Http Ssl Configuration object.`,
						},
						"cli_only_mode": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							Validators: []validator.String{
								stringvalidator.OneOf("disabled", "enabled"),
							},
							MarkdownDescription: `CLI only mode.`,
						},
						"client_cert_auth_state": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							Validators: []validator.String{
								stringvalidator.OneOf("disabled", "enabled"),
							},
							MarkdownDescription: `Client Cert Auth State.`,
						},
						"description": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The description of the Http Ssl Configuration object.`,
						},
						"dh_param": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							Validators: []validator.String{
								stringvalidator.OneOf("1024", "2048", "4096", "none"),
							},
							MarkdownDescription: `DH Parameter.`,
						},
						"global_throttle_rate": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The maximum MO api calls allowed per unit time.`,
						},
						"global_throttle_st": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							Validators: []validator.String{
								stringvalidator.OneOf("disabled", "enabled"),
							},
							MarkdownDescription: `Throttle state for all clients without tag0 in header.`,
						},
						"global_throttle_unit": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `Unit of rate limit.`,
						},
						"max_request_status_count": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The maximum number of request status objects to keep.`,
						},
						"name": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The name of the Http Ssl Configuration object.`,
						},
						"name_alias": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The name alias of the Http Ssl Configuration object.`,
						},
						"node_exporter": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							Validators: []validator.String{
								stringvalidator.OneOf("disabled", "enabled"),
							},
							MarkdownDescription: `Node Exporter service.`,
						},
						"port": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The port used for HTTPS communication service.`,
						},
						"referer": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `Allowed HTTP referer space separated list.`,
						},
						"server_header": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							Validators: []validator.String{
								stringvalidator.OneOf("disabled", "enabled"),
							},
							MarkdownDescription: `Server Header.`,
						},
						"ssl_protocols": schema.SetAttribute{
							MarkdownDescription: `The Secure Socket Layer (SSL) protocol.`,
							Optional:            true,
							Computed:            true,
							PlanModifiers: []planmodifier.Set{
								setplanmodifier.UseStateForUnknown(),
							},
							Validators: []validator.Set{
								setvalidator.SizeAtMost(4),
								setvalidator.ValueStringsAre(
									stringvalidator.OneOf("TLSv1", "TLSv1.1", "TLSv1.2", "TLSv1.3"),
								),
							},
							ElementType: types.StringType,
						},
						"throttle_rate": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The maximum login/refresh allowed per second.`,
						},
						"throttle_st": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							Validators: []validator.String{
								stringvalidator.OneOf("disabled", "enabled"),
							},
							MarkdownDescription: `Login/refresh throttle state.`,
						},
						"visore_access": schema.StringAttribute{
							Optional: true,
							Computed: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							Validators: []validator.String{
								stringvalidator.OneOf("disabled", "enabled"),
							},
							MarkdownDescription: `Visore Access.`,
						},
						"tp": schema.SetNestedAttribute{
							MarkdownDescription: ``,
							Optional:            true,
							Computed:            true,
							PlanModifiers: []planmodifier.Set{
								setplanmodifier.UseStateForUnknown(),
							},
							Validators: []validator.Set{
								setvalidator.SizeAtMost(1),
							},
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"annotation": schema.StringAttribute{
										Optional: true,
										Computed: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
											SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
										},
										MarkdownDescription: `The annotation of the Tp object.`,
									},
									"target_dn": schema.StringAttribute{
										Optional: true,
										Computed: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
											SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
										},
										MarkdownDescription: `The distinguished name of the target.`,
									},
									"annotations": schema.SetNestedAttribute{
										MarkdownDescription: ``,
										Optional:            true,
										Computed:            true,
										PlanModifiers: []planmodifier.Set{
											setplanmodifier.UseStateForUnknown(),
										},
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"key": schema.StringAttribute{
													Required: true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
														SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
													},
													MarkdownDescription: `The key used to uniquely identify this configuration object.`,
												},
												"value": schema.StringAttribute{
													Required: true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
														SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
													},
													MarkdownDescription: `The value of the property.`,
												},
											},
										},
									},
									"tags": schema.SetNestedAttribute{
										MarkdownDescription: ``,
										Optional:            true,
										Computed:            true,
										PlanModifiers: []planmodifier.Set{
											setplanmodifier.UseStateForUnknown(),
										},
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"key": schema.StringAttribute{
													Required: true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
														SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
													},
													MarkdownDescription: `The key used to uniquely identify this configuration object.`,
												},
												"value": schema.StringAttribute{
													Required: true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
														SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
													},
													MarkdownDescription: `The value of the property.`,
												},
											},
										},
									},
								},
							},
						},
						"key_ring": schema.SetNestedAttribute{
							MarkdownDescription: `A source relation to a key ring.`,
							Optional:            true,
							Computed:            true,
							PlanModifiers: []planmodifier.Set{
								setplanmodifier.UseStateForUnknown(),
							},
							Validators: []validator.Set{
								setvalidator.SizeAtMost(1),
							},
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"annotation": schema.StringAttribute{
										Optional: true,
										Computed: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
											SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
										},
										MarkdownDescription: `The annotation of the Key Ring object.`,
									},
									"tn_pki_key_ring_name": schema.StringAttribute{
										Optional: true,
										Computed: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
											SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
										},
										MarkdownDescription: `The HTTP connection key ring. Each PKI device holds a pair of asymmetric Rivest-Shamir-Adleman (RSA) or Elliptic Curve Cryptography (ECC) encryption keys, one kept private and one made public, stored in an internal key ring.`,
									},
									"annotations": schema.SetNestedAttribute{
										MarkdownDescription: ``,
										Optional:            true,
										Computed:            true,
										PlanModifiers: []planmodifier.Set{
											setplanmodifier.UseStateForUnknown(),
										},
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"key": schema.StringAttribute{
													Required: true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
														SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
													},
													MarkdownDescription: `The key used to uniquely identify this configuration object.`,
												},
												"value": schema.StringAttribute{
													Required: true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
														SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
													},
													MarkdownDescription: `The value of the property.`,
												},
											},
										},
									},
									"tags": schema.SetNestedAttribute{
										MarkdownDescription: ``,
										Optional:            true,
										Computed:            true,
										PlanModifiers: []planmodifier.Set{
											setplanmodifier.UseStateForUnknown(),
										},
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"key": schema.StringAttribute{
													Required: true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
														SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
													},
													MarkdownDescription: `The key used to uniquely identify this configuration object.`,
												},
												"value": schema.StringAttribute{
													Required: true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
														SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
													},
													MarkdownDescription: `The value of the property.`,
												},
											},
										},
									},
								},
							},
						},
						"annotations": schema.SetNestedAttribute{
							MarkdownDescription: ``,
							Optional:            true,
							Computed:            true,
							PlanModifiers: []planmodifier.Set{
								setplanmodifier.UseStateForUnknown(),
							},
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"key": schema.StringAttribute{
										Required: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
											SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
										},
										MarkdownDescription: `The key used to uniquely identify this configuration object.`,
									},
									"value": schema.StringAttribute{
										Required: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
											SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
										},
										MarkdownDescription: `The value of the property.`,
									},
								},
							},
						},
						"tags": schema.SetNestedAttribute{
							MarkdownDescription: ``,
							Optional:            true,
							Computed:            true,
							PlanModifiers: []planmodifier.Set{
								setplanmodifier.UseStateForUnknown(),
							},
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"key": schema.StringAttribute{
										Required: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
											SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
										},
										MarkdownDescription: `The key used to uniquely identify this configuration object.`,
									},
									"value": schema.StringAttribute{
										Required: true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
											SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
										},
										MarkdownDescription: `The value of the property.`,
									},
								},
							},
						},
					},
				},
			},
			"annotations": schema.SetNestedAttribute{
				MarkdownDescription: ``,
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"key": schema.StringAttribute{
							Required: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The key used to uniquely identify this configuration object.`,
						},
						"value": schema.StringAttribute{
							Required: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The value of the property.`,
						},
					},
				},
			},
			"tags": schema.SetNestedAttribute{
				MarkdownDescription: ``,
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"key": schema.StringAttribute{
							Required: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The key used to uniquely identify this configuration object.`,
						},
						"value": schema.StringAttribute{
							Required: true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
								SetToStringNullWhenStateIsNullPlanIsUnknownDuringUpdate(),
							},
							MarkdownDescription: `The value of the property.`,
						},
					},
				},
			},
		},
	}
	tflog.Debug(ctx, "End schema of resource: aci_communication_policy")
}

func (r *CommPolResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	tflog.Debug(ctx, "Start configure of resource: aci_communication_policy")
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
	tflog.Debug(ctx, "End configure of resource: aci_communication_policy")
}

func (r *CommPolResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Debug(ctx, "Start create of resource: aci_communication_policy")
	// On create retrieve information on current state prior to making any changes in order to determine child delete operations
	var stateData *CommPolResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &stateData)...)
	setCommPolId(ctx, stateData)
	getAndSetCommPolAttributes(ctx, &resp.Diagnostics, r.client, stateData)

	var data *CommPolResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	setCommPolId(ctx, data)

	tflog.Debug(ctx, fmt.Sprintf("Create of resource aci_communication_policy with id '%s'", data.Id.ValueString()))

	var commHttpsPlan, commHttpsState []CommHttpsCommPolResourceModel
	data.CommHttps.ElementsAs(ctx, &commHttpsPlan, false)
	stateData.CommHttps.ElementsAs(ctx, &commHttpsState, false)
	var tagAnnotationPlan, tagAnnotationState []TagAnnotationCommPolResourceModel
	data.TagAnnotation.ElementsAs(ctx, &tagAnnotationPlan, false)
	stateData.TagAnnotation.ElementsAs(ctx, &tagAnnotationState, false)
	var tagTagPlan, tagTagState []TagTagCommPolResourceModel
	data.TagTag.ElementsAs(ctx, &tagTagPlan, false)
	stateData.TagTag.ElementsAs(ctx, &tagTagState, false)
	jsonPayload := getCommPolCreateJsonPayload(ctx, &resp.Diagnostics, data, commHttpsPlan, commHttpsState, tagAnnotationPlan, tagAnnotationState, tagTagPlan, tagTagState)

	if resp.Diagnostics.HasError() {
		return
	}

	DoRestRequest(ctx, &resp.Diagnostics, r.client, fmt.Sprintf("api/mo/%s.json", data.Id.ValueString()), "POST", jsonPayload)
	if resp.Diagnostics.HasError() {
		return
	}

	getAndSetCommPolAttributes(ctx, &resp.Diagnostics, r.client, data)

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	tflog.Debug(ctx, fmt.Sprintf("End create of resource aci_communication_policy with id '%s'", data.Id.ValueString()))
}

func (r *CommPolResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	tflog.Debug(ctx, "Start read of resource: aci_communication_policy")
	var data *CommPolResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Read of resource aci_communication_policy with id '%s'", data.Id.ValueString()))

	getAndSetCommPolAttributes(ctx, &resp.Diagnostics, r.client, data)

	// Save updated data into Terraform state
	if data.Id.IsNull() {
		var emptyData *CommPolResourceModel
		resp.Diagnostics.Append(resp.State.Set(ctx, &emptyData)...)
	} else {
		resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	}

	tflog.Debug(ctx, fmt.Sprintf("End read of resource aci_communication_policy with id '%s'", data.Id.ValueString()))
}

func (r *CommPolResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	tflog.Debug(ctx, "Start update of resource: aci_communication_policy")
	var data *CommPolResourceModel
	var stateData *CommPolResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &stateData)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Update of resource aci_communication_policy with id '%s'", data.Id.ValueString()))

	var commHttpsPlan, commHttpsState []CommHttpsCommPolResourceModel
	data.CommHttps.ElementsAs(ctx, &commHttpsPlan, false)
	stateData.CommHttps.ElementsAs(ctx, &commHttpsState, false)
	var tagAnnotationPlan, tagAnnotationState []TagAnnotationCommPolResourceModel
	data.TagAnnotation.ElementsAs(ctx, &tagAnnotationPlan, false)
	stateData.TagAnnotation.ElementsAs(ctx, &tagAnnotationState, false)
	var tagTagPlan, tagTagState []TagTagCommPolResourceModel
	data.TagTag.ElementsAs(ctx, &tagTagPlan, false)
	stateData.TagTag.ElementsAs(ctx, &tagTagState, false)
	jsonPayload := getCommPolCreateJsonPayload(ctx, &resp.Diagnostics, data, commHttpsPlan, commHttpsState, tagAnnotationPlan, tagAnnotationState, tagTagPlan, tagTagState)

	if resp.Diagnostics.HasError() {
		return
	}

	DoRestRequest(ctx, &resp.Diagnostics, r.client, fmt.Sprintf("api/mo/%s.json", data.Id.ValueString()), "POST", jsonPayload)

	if resp.Diagnostics.HasError() {
		return
	}

	getAndSetCommPolAttributes(ctx, &resp.Diagnostics, r.client, data)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	tflog.Debug(ctx, fmt.Sprintf("End update of resource aci_communication_policy with id '%s'", data.Id.ValueString()))
}

func (r *CommPolResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	tflog.Debug(ctx, "Start delete of resource: aci_communication_policy")
	var data *CommPolResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Delete of resource aci_communication_policy with id '%s'", data.Id.ValueString()))
	jsonPayload := GetDeleteJsonPayload(ctx, &resp.Diagnostics, "commPol", data.Id.ValueString())
	if resp.Diagnostics.HasError() {
		return
	}
	DoRestRequest(ctx, &resp.Diagnostics, r.client, fmt.Sprintf("api/mo/%s.json", data.Id.ValueString()), "POST", jsonPayload)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, fmt.Sprintf("End delete of resource aci_communication_policy with id '%s'", data.Id.ValueString()))
}

func (r *CommPolResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Debug(ctx, "Start import state of resource: aci_communication_policy")
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)

	var stateData *CommPolResourceModel
	resp.Diagnostics.Append(resp.State.Get(ctx, &stateData)...)
	tflog.Debug(ctx, fmt.Sprintf("Import state of resource aci_communication_policy with id '%s'", stateData.Id.ValueString()))

	tflog.Debug(ctx, "End import of state resource: aci_communication_policy")
}

func getAndSetCommPolAttributes(ctx context.Context, diags *diag.Diagnostics, client *client.Client, data *CommPolResourceModel) {
	requestData := DoRestRequest(ctx, diags, client, fmt.Sprintf("api/mo/%s.json?rsp-subtree=full&rsp-subtree-class=%s", data.Id.ValueString(), "commPol,commHttps,tagAnnotation,tagTag,commRsClientCertCA,commRsKeyRing,tagAnnotation,tagTag,tagAnnotation,tagTag,tagAnnotation,tagTag"), "GET", nil)

	if diags.HasError() {
		return
	}
	if requestData.Search("imdata").Search("commPol").Data() != nil {
		classReadInfo := requestData.Search("imdata").Search("commPol").Data().([]interface{})
		if len(classReadInfo) == 1 {
			attributes := classReadInfo[0].(map[string]interface{})["attributes"].(map[string]interface{})
			for attributeName, attributeValue := range attributes {
				if attributeName == "dn" {
					data.Id = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "annotation" {
					data.Annotation = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "descr" {
					data.Descr = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "name" {
					data.Name = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "nameAlias" {
					data.NameAlias = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "ownerKey" {
					data.OwnerKey = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "ownerTag" {
					data.OwnerTag = basetypes.NewStringValue(attributeValue.(string))
				}
				if attributeName == "strictSecurityOnApicOOBSubnet" {
					data.StrictSecurityOnApicOOBSubnet = basetypes.NewStringValue(attributeValue.(string))
				}
			}
			if data.Annotation.IsUnknown() {
				data.Annotation = types.StringNull()
			}
			if data.Descr.IsUnknown() {
				data.Descr = types.StringNull()
			}
			if data.Name.IsUnknown() {
				data.Name = types.StringNull()
			}
			if data.NameAlias.IsUnknown() {
				data.NameAlias = types.StringNull()
			}
			if data.OwnerKey.IsUnknown() {
				data.OwnerKey = types.StringNull()
			}
			if data.OwnerTag.IsUnknown() {
				data.OwnerTag = types.StringNull()
			}
			if data.StrictSecurityOnApicOOBSubnet.IsUnknown() {
				data.StrictSecurityOnApicOOBSubnet = types.StringNull()
			}
			CommHttpsCommPol := CommHttpsCommPolResourceModel{}
			CommHttpsCommPolList := make([]CommHttpsCommPolResourceModel, 0)
			CommRsClientCertCACommHttpsCommPol := CommRsClientCertCACommHttpsCommPolResourceModel{}
			CommRsClientCertCACommHttpsCommPolList := make([]CommRsClientCertCACommHttpsCommPolResourceModel, 0)
			TagAnnotationCommRsClientCertCACommHttpsCommPol := TagAnnotationCommRsClientCertCACommHttpsCommPolResourceModel{}
			TagAnnotationCommRsClientCertCACommHttpsCommPolList := make([]TagAnnotationCommRsClientCertCACommHttpsCommPolResourceModel, 0)
			TagTagCommRsClientCertCACommHttpsCommPol := TagTagCommRsClientCertCACommHttpsCommPolResourceModel{}
			TagTagCommRsClientCertCACommHttpsCommPolList := make([]TagTagCommRsClientCertCACommHttpsCommPolResourceModel, 0)
			CommRsKeyRingCommHttpsCommPol := CommRsKeyRingCommHttpsCommPolResourceModel{}
			CommRsKeyRingCommHttpsCommPolList := make([]CommRsKeyRingCommHttpsCommPolResourceModel, 0)
			TagAnnotationCommRsKeyRingCommHttpsCommPol := TagAnnotationCommRsKeyRingCommHttpsCommPolResourceModel{}
			TagAnnotationCommRsKeyRingCommHttpsCommPolList := make([]TagAnnotationCommRsKeyRingCommHttpsCommPolResourceModel, 0)
			TagTagCommRsKeyRingCommHttpsCommPol := TagTagCommRsKeyRingCommHttpsCommPolResourceModel{}
			TagTagCommRsKeyRingCommHttpsCommPolList := make([]TagTagCommRsKeyRingCommHttpsCommPolResourceModel, 0)
			TagAnnotationCommHttpsCommPol := TagAnnotationCommHttpsCommPolResourceModel{}
			TagAnnotationCommHttpsCommPolList := make([]TagAnnotationCommHttpsCommPolResourceModel, 0)
			TagTagCommHttpsCommPol := TagTagCommHttpsCommPolResourceModel{}
			TagTagCommHttpsCommPolList := make([]TagTagCommHttpsCommPolResourceModel, 0)
			TagAnnotationCommPol := TagAnnotationCommPolResourceModel{}
			TagAnnotationCommPolList := make([]TagAnnotationCommPolResourceModel, 0)
			TagTagCommPol := TagTagCommPolResourceModel{}
			TagTagCommPolList := make([]TagTagCommPolResourceModel, 0)
			_, ok := classReadInfo[0].(map[string]interface{})["children"]
			if ok {
				children := classReadInfo[0].(map[string]interface{})["children"].([]interface{})
				for _, child := range children {
					for childClassName, childClassDetails := range child.(map[string]interface{}) {
						childAttributes := childClassDetails.(map[string]interface{})["attributes"].(map[string]interface{})
						if childClassName == "commHttps" {
							for childAttributeName, childAttributeValue := range childAttributes {
								if childAttributeName == "accessControlAllowCredential" {
									CommHttpsCommPol.AccessControlAllowCredential = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "accessControlAllowOrigins" {
									CommHttpsCommPol.AccessControlAllowOrigins = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "adminSt" {
									CommHttpsCommPol.AdminSt = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "annotation" {
									CommHttpsCommPol.Annotation = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "cliOnlyMode" {
									CommHttpsCommPol.CliOnlyMode = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "clientCertAuthState" {
									CommHttpsCommPol.ClientCertAuthState = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "descr" {
									CommHttpsCommPol.Descr = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "dhParam" && childAttributeValue.(string) == "" {
									CommHttpsCommPol.DhParam = basetypes.NewStringValue("none")
								} else if childAttributeName == "dhParam" {
									CommHttpsCommPol.DhParam = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "globalThrottleRate" {
									CommHttpsCommPol.GlobalThrottleRate = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "globalThrottleSt" {
									CommHttpsCommPol.GlobalThrottleSt = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "globalThrottleUnit" {
									CommHttpsCommPol.GlobalThrottleUnit = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "maxRequestStatusCount" {
									CommHttpsCommPol.MaxRequestStatusCount = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "name" {
									CommHttpsCommPol.Name = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "nameAlias" {
									CommHttpsCommPol.NameAlias = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "nodeExporter" {
									CommHttpsCommPol.NodeExporter = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "port" {
									CommHttpsCommPol.Port = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "referer" {
									CommHttpsCommPol.Referer = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "serverHeader" {
									CommHttpsCommPol.ServerHeader = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "sslProtocols" {
									sslProtocolsList := strings.Split(childAttributeValue.(string), ",")
									sslProtocolsSet, _ := types.SetValueFrom(ctx, basetypes.StringType{}, sslProtocolsList)
									CommHttpsCommPol.SslProtocols = sslProtocolsSet

								}
								if childAttributeName == "throttleRate" {
									CommHttpsCommPol.ThrottleRate = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "throttleSt" {
									CommHttpsCommPol.ThrottleSt = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "visoreAccess" {
									CommHttpsCommPol.VisoreAccess = basetypes.NewStringValue(childAttributeValue.(string))
								}

							}
							childrenOfCommHttpsCommPol, childrenOfCommHttpsCommPolExist := childClassDetails.(map[string]interface{})["children"]
							if childrenOfCommHttpsCommPolExist {
								for _, childCommHttpsCommPol := range childrenOfCommHttpsCommPol.([]interface{}) {
									for childClassNameCommHttpsCommPol, childClassDetailsCommHttpsCommPol := range childCommHttpsCommPol.(map[string]interface{}) {
										if childClassNameCommHttpsCommPol == "commRsClientCertCA" {
											commRsClientCertCAchildAttributeValue := childClassDetailsCommHttpsCommPol.(map[string]interface{})["attributes"].(map[string]interface{})
											for childAttributeName, childAttributeValue := range commRsClientCertCAchildAttributeValue {
												if childAttributeName == "annotation" {
													CommRsClientCertCACommHttpsCommPol.Annotation = basetypes.NewStringValue(childAttributeValue.(string))
												}
												if childAttributeName == "tDn" {
													CommRsClientCertCACommHttpsCommPol.TDn = basetypes.NewStringValue(childAttributeValue.(string))
												}
											}
											childrenOfCommRsClientCertCACommHttpsCommPol, childrenOfCommRsClientCertCACommHttpsCommPolExist := childClassDetailsCommHttpsCommPol.(map[string]interface{})["children"]
											if childrenOfCommRsClientCertCACommHttpsCommPolExist {
												for _, childCommRsClientCertCACommHttpsCommPol := range childrenOfCommRsClientCertCACommHttpsCommPol.([]interface{}) {
													for childClassNameCommRsClientCertCACommHttpsCommPol, childClassDetailsCommRsClientCertCACommHttpsCommPol := range childCommRsClientCertCACommHttpsCommPol.(map[string]interface{}) {
														if childClassNameCommRsClientCertCACommHttpsCommPol == "tagAnnotation" {
															tagAnnotationchildAttributeValue := childClassDetailsCommRsClientCertCACommHttpsCommPol.(map[string]interface{})["attributes"].(map[string]interface{})
															for childAttributeName, childAttributeValue := range tagAnnotationchildAttributeValue {
																if childAttributeName == "key" {
																	TagAnnotationCommRsClientCertCACommHttpsCommPol.Key = basetypes.NewStringValue(childAttributeValue.(string))
																}
																if childAttributeName == "value" {
																	TagAnnotationCommRsClientCertCACommHttpsCommPol.Value = basetypes.NewStringValue(childAttributeValue.(string))
																}
															}
															TagAnnotationCommRsClientCertCACommHttpsCommPolList = append(TagAnnotationCommRsClientCertCACommHttpsCommPolList, TagAnnotationCommRsClientCertCACommHttpsCommPol)
														}
														if childClassNameCommRsClientCertCACommHttpsCommPol == "tagTag" {
															tagTagchildAttributeValue := childClassDetailsCommRsClientCertCACommHttpsCommPol.(map[string]interface{})["attributes"].(map[string]interface{})
															for childAttributeName, childAttributeValue := range tagTagchildAttributeValue {
																if childAttributeName == "key" {
																	TagTagCommRsClientCertCACommHttpsCommPol.Key = basetypes.NewStringValue(childAttributeValue.(string))
																}
																if childAttributeName == "value" {
																	TagTagCommRsClientCertCACommHttpsCommPol.Value = basetypes.NewStringValue(childAttributeValue.(string))
																}
															}
															TagTagCommRsClientCertCACommHttpsCommPolList = append(TagTagCommRsClientCertCACommHttpsCommPolList, TagTagCommRsClientCertCACommHttpsCommPol)
														}
													}
												}
											}
											TagAnnotationSet, _ := types.SetValueFrom(ctx, TagAnnotationCommRsClientCertCACommHttpsCommPolResourceModelElementType(), TagAnnotationCommRsClientCertCACommHttpsCommPolList)
											CommRsClientCertCACommHttpsCommPol.TagAnnotation = TagAnnotationSet
											TagTagSet, _ := types.SetValueFrom(ctx, TagTagCommRsClientCertCACommHttpsCommPolResourceModelElementType(), TagTagCommRsClientCertCACommHttpsCommPolList)
											CommRsClientCertCACommHttpsCommPol.TagTag = TagTagSet
											CommRsClientCertCACommHttpsCommPolList = append(CommRsClientCertCACommHttpsCommPolList, CommRsClientCertCACommHttpsCommPol)
										}
										if childClassNameCommHttpsCommPol == "commRsKeyRing" {
											commRsKeyRingchildAttributeValue := childClassDetailsCommHttpsCommPol.(map[string]interface{})["attributes"].(map[string]interface{})
											for childAttributeName, childAttributeValue := range commRsKeyRingchildAttributeValue {
												if childAttributeName == "annotation" {
													CommRsKeyRingCommHttpsCommPol.Annotation = basetypes.NewStringValue(childAttributeValue.(string))
												}
												if childAttributeName == "tnPkiKeyRingName" {
													CommRsKeyRingCommHttpsCommPol.TnPkiKeyRingName = basetypes.NewStringValue(childAttributeValue.(string))
												}
											}
											childrenOfCommRsKeyRingCommHttpsCommPol, childrenOfCommRsKeyRingCommHttpsCommPolExist := childClassDetailsCommHttpsCommPol.(map[string]interface{})["children"]
											if childrenOfCommRsKeyRingCommHttpsCommPolExist {
												for _, childCommRsKeyRingCommHttpsCommPol := range childrenOfCommRsKeyRingCommHttpsCommPol.([]interface{}) {
													for childClassNameCommRsKeyRingCommHttpsCommPol, childClassDetailsCommRsKeyRingCommHttpsCommPol := range childCommRsKeyRingCommHttpsCommPol.(map[string]interface{}) {
														if childClassNameCommRsKeyRingCommHttpsCommPol == "tagAnnotation" {
															tagAnnotationchildAttributeValue := childClassDetailsCommRsKeyRingCommHttpsCommPol.(map[string]interface{})["attributes"].(map[string]interface{})
															for childAttributeName, childAttributeValue := range tagAnnotationchildAttributeValue {
																if childAttributeName == "key" {
																	TagAnnotationCommRsKeyRingCommHttpsCommPol.Key = basetypes.NewStringValue(childAttributeValue.(string))
																}
																if childAttributeName == "value" {
																	TagAnnotationCommRsKeyRingCommHttpsCommPol.Value = basetypes.NewStringValue(childAttributeValue.(string))
																}
															}
															TagAnnotationCommRsKeyRingCommHttpsCommPolList = append(TagAnnotationCommRsKeyRingCommHttpsCommPolList, TagAnnotationCommRsKeyRingCommHttpsCommPol)
														}
														if childClassNameCommRsKeyRingCommHttpsCommPol == "tagTag" {
															tagTagchildAttributeValue := childClassDetailsCommRsKeyRingCommHttpsCommPol.(map[string]interface{})["attributes"].(map[string]interface{})
															for childAttributeName, childAttributeValue := range tagTagchildAttributeValue {
																if childAttributeName == "key" {
																	TagTagCommRsKeyRingCommHttpsCommPol.Key = basetypes.NewStringValue(childAttributeValue.(string))
																}
																if childAttributeName == "value" {
																	TagTagCommRsKeyRingCommHttpsCommPol.Value = basetypes.NewStringValue(childAttributeValue.(string))
																}
															}
															TagTagCommRsKeyRingCommHttpsCommPolList = append(TagTagCommRsKeyRingCommHttpsCommPolList, TagTagCommRsKeyRingCommHttpsCommPol)
														}
													}
												}
											}
											TagAnnotationSet, _ := types.SetValueFrom(ctx, TagAnnotationCommRsKeyRingCommHttpsCommPolResourceModelElementType(), TagAnnotationCommRsKeyRingCommHttpsCommPolList)
											CommRsKeyRingCommHttpsCommPol.TagAnnotation = TagAnnotationSet
											TagTagSet, _ := types.SetValueFrom(ctx, TagTagCommRsKeyRingCommHttpsCommPolResourceModelElementType(), TagTagCommRsKeyRingCommHttpsCommPolList)
											CommRsKeyRingCommHttpsCommPol.TagTag = TagTagSet
											CommRsKeyRingCommHttpsCommPolList = append(CommRsKeyRingCommHttpsCommPolList, CommRsKeyRingCommHttpsCommPol)
										}
										if childClassNameCommHttpsCommPol == "tagAnnotation" {
											tagAnnotationchildAttributeValue := childClassDetailsCommHttpsCommPol.(map[string]interface{})["attributes"].(map[string]interface{})
											for childAttributeName, childAttributeValue := range tagAnnotationchildAttributeValue {
												if childAttributeName == "key" {
													TagAnnotationCommHttpsCommPol.Key = basetypes.NewStringValue(childAttributeValue.(string))
												}
												if childAttributeName == "value" {
													TagAnnotationCommHttpsCommPol.Value = basetypes.NewStringValue(childAttributeValue.(string))
												}
											}
											TagAnnotationCommHttpsCommPolList = append(TagAnnotationCommHttpsCommPolList, TagAnnotationCommHttpsCommPol)
										}
										if childClassNameCommHttpsCommPol == "tagTag" {
											tagTagchildAttributeValue := childClassDetailsCommHttpsCommPol.(map[string]interface{})["attributes"].(map[string]interface{})
											for childAttributeName, childAttributeValue := range tagTagchildAttributeValue {
												if childAttributeName == "key" {
													TagTagCommHttpsCommPol.Key = basetypes.NewStringValue(childAttributeValue.(string))
												}
												if childAttributeName == "value" {
													TagTagCommHttpsCommPol.Value = basetypes.NewStringValue(childAttributeValue.(string))
												}
											}
											TagTagCommHttpsCommPolList = append(TagTagCommHttpsCommPolList, TagTagCommHttpsCommPol)
										}
									}
								}
							}
							CommRsClientCertCASet, _ := types.SetValueFrom(ctx, CommRsClientCertCACommHttpsCommPolResourceModelElementType(), CommRsClientCertCACommHttpsCommPolList)
							CommHttpsCommPol.CommRsClientCertCA = CommRsClientCertCASet
							CommRsKeyRingSet, _ := types.SetValueFrom(ctx, CommRsKeyRingCommHttpsCommPolResourceModelElementType(), CommRsKeyRingCommHttpsCommPolList)
							CommHttpsCommPol.CommRsKeyRing = CommRsKeyRingSet
							TagAnnotationSet, _ := types.SetValueFrom(ctx, TagAnnotationCommHttpsCommPolResourceModelElementType(), TagAnnotationCommHttpsCommPolList)
							CommHttpsCommPol.TagAnnotation = TagAnnotationSet
							TagTagSet, _ := types.SetValueFrom(ctx, TagTagCommHttpsCommPolResourceModelElementType(), TagTagCommHttpsCommPolList)
							CommHttpsCommPol.TagTag = TagTagSet
							CommHttpsCommPolList = append(CommHttpsCommPolList, CommHttpsCommPol)
						}
						if childClassName == "tagAnnotation" {
							for childAttributeName, childAttributeValue := range childAttributes {
								if childAttributeName == "key" {
									TagAnnotationCommPol.Key = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "value" {
									TagAnnotationCommPol.Value = basetypes.NewStringValue(childAttributeValue.(string))
								}

							}
							TagAnnotationCommPolList = append(TagAnnotationCommPolList, TagAnnotationCommPol)
						}
						if childClassName == "tagTag" {
							for childAttributeName, childAttributeValue := range childAttributes {
								if childAttributeName == "key" {
									TagTagCommPol.Key = basetypes.NewStringValue(childAttributeValue.(string))
								}
								if childAttributeName == "value" {
									TagTagCommPol.Value = basetypes.NewStringValue(childAttributeValue.(string))
								}

							}
							TagTagCommPolList = append(TagTagCommPolList, TagTagCommPol)
						}
					}
				}
			}
			commHttpsSet, _ := types.SetValueFrom(ctx, data.CommHttps.ElementType(ctx), CommHttpsCommPolList)
			data.CommHttps = commHttpsSet
			tagAnnotationSet, _ := types.SetValueFrom(ctx, data.TagAnnotation.ElementType(ctx), TagAnnotationCommPolList)
			data.TagAnnotation = tagAnnotationSet
			tagTagSet, _ := types.SetValueFrom(ctx, data.TagTag.ElementType(ctx), TagTagCommPolList)
			data.TagTag = tagTagSet
		} else {
			diags.AddError(
				"too many results in response",
				fmt.Sprintf("%v matches returned for class 'commPol'. Please report this issue to the provider developers.", len(classReadInfo)),
			)
		}
	} else {
		data.Id = basetypes.NewStringNull()
	}
}

func getCommPolRn(ctx context.Context, data *CommPolResourceModel) string {
	rn := "fabric/comm-{name}"
	for _, identifier := range []string{"name"} {
		fieldName := fmt.Sprintf("%s%s", strings.ToUpper(identifier[:1]), identifier[1:])
		fieldValue := reflect.ValueOf(data).Elem().FieldByName(fieldName).Interface().(basetypes.StringValue).ValueString()
		rn = strings.ReplaceAll(rn, fmt.Sprintf("{%s}", identifier), fieldValue)
	}
	return rn
}

func setCommPolId(ctx context.Context, data *CommPolResourceModel) {
	rn := getCommPolRn(ctx, data)
	data.Id = types.StringValue(fmt.Sprintf("%s/%s", strings.Split([]string{"uni/fabric/comm-{name}"}[0], "/")[0], rn))
}

func getCommPolCommHttpsChildPayloads(ctx context.Context, diags *diag.Diagnostics, data *CommPolResourceModel, commHttpsCommPolPlan, commHttpsCommPolState []CommHttpsCommPolResourceModel) []map[string]interface{} {
	childMap := NewAciObject()
	childPayloads := []map[string]interface{}{}
	commRsClientCertCACommHttpsCommPolChildMap := NewAciObject()
	tagAnnotationCommRsClientCertCACommHttpsCommPolChildMap := NewAciObject()
	tagTagCommRsClientCertCACommHttpsCommPolChildMap := NewAciObject()
	CommRsClientCertCACommHttpsCommPolChildren := make([]map[string]interface{}, 0)
	commRsKeyRingCommHttpsCommPolChildMap := NewAciObject()
	tagAnnotationCommRsKeyRingCommHttpsCommPolChildMap := NewAciObject()
	tagTagCommRsKeyRingCommHttpsCommPolChildMap := NewAciObject()
	CommRsKeyRingCommHttpsCommPolChildren := make([]map[string]interface{}, 0)
	tagAnnotationCommHttpsCommPolChildMap := NewAciObject()
	tagTagCommHttpsCommPolChildMap := NewAciObject()
	CommHttpsCommPolChildren := make([]map[string]interface{}, 0)
	if !data.CommHttps.IsNull() && !data.CommHttps.IsUnknown() {
		for _, commHttpsCommPol := range commHttpsCommPolPlan {
			if !commHttpsCommPol.AccessControlAllowCredential.IsNull() && !commHttpsCommPol.AccessControlAllowCredential.IsUnknown() {
				childMap.Attributes["accessControlAllowCredential"] = commHttpsCommPol.AccessControlAllowCredential.ValueString()
			}
			if !commHttpsCommPol.AccessControlAllowOrigins.IsNull() && !commHttpsCommPol.AccessControlAllowOrigins.IsUnknown() {
				childMap.Attributes["accessControlAllowOrigins"] = commHttpsCommPol.AccessControlAllowOrigins.ValueString()
			}
			if !commHttpsCommPol.AdminSt.IsNull() && !commHttpsCommPol.AdminSt.IsUnknown() {
				childMap.Attributes["adminSt"] = commHttpsCommPol.AdminSt.ValueString()
			}
			if !commHttpsCommPol.Annotation.IsNull() && !commHttpsCommPol.Annotation.IsUnknown() {
				childMap.Attributes["annotation"] = commHttpsCommPol.Annotation.ValueString()
			} else {
				childMap.Attributes["annotation"] = globalAnnotation
			}
			if !commHttpsCommPol.CliOnlyMode.IsNull() && !commHttpsCommPol.CliOnlyMode.IsUnknown() {
				childMap.Attributes["cliOnlyMode"] = commHttpsCommPol.CliOnlyMode.ValueString()
			}
			if !commHttpsCommPol.ClientCertAuthState.IsNull() && !commHttpsCommPol.ClientCertAuthState.IsUnknown() {
				childMap.Attributes["clientCertAuthState"] = commHttpsCommPol.ClientCertAuthState.ValueString()
			}
			if !commHttpsCommPol.Descr.IsNull() && !commHttpsCommPol.Descr.IsUnknown() {
				childMap.Attributes["descr"] = commHttpsCommPol.Descr.ValueString()
			}
			if !commHttpsCommPol.DhParam.IsNull() && !commHttpsCommPol.DhParam.IsUnknown() {
				childMap.Attributes["dhParam"] = commHttpsCommPol.DhParam.ValueString()
			}
			if !commHttpsCommPol.GlobalThrottleRate.IsNull() && !commHttpsCommPol.GlobalThrottleRate.IsUnknown() {
				childMap.Attributes["globalThrottleRate"] = commHttpsCommPol.GlobalThrottleRate.ValueString()
			}
			if !commHttpsCommPol.GlobalThrottleSt.IsNull() && !commHttpsCommPol.GlobalThrottleSt.IsUnknown() {
				childMap.Attributes["globalThrottleSt"] = commHttpsCommPol.GlobalThrottleSt.ValueString()
			}
			if !commHttpsCommPol.GlobalThrottleUnit.IsNull() && !commHttpsCommPol.GlobalThrottleUnit.IsUnknown() {
				childMap.Attributes["globalThrottleUnit"] = commHttpsCommPol.GlobalThrottleUnit.ValueString()
			}
			if !commHttpsCommPol.MaxRequestStatusCount.IsNull() && !commHttpsCommPol.MaxRequestStatusCount.IsUnknown() {
				childMap.Attributes["maxRequestStatusCount"] = commHttpsCommPol.MaxRequestStatusCount.ValueString()
			}
			if !commHttpsCommPol.Name.IsNull() && !commHttpsCommPol.Name.IsUnknown() {
				childMap.Attributes["name"] = commHttpsCommPol.Name.ValueString()
			}
			if !commHttpsCommPol.NameAlias.IsNull() && !commHttpsCommPol.NameAlias.IsUnknown() {
				childMap.Attributes["nameAlias"] = commHttpsCommPol.NameAlias.ValueString()
			}
			if !commHttpsCommPol.NodeExporter.IsNull() && !commHttpsCommPol.NodeExporter.IsUnknown() {
				childMap.Attributes["nodeExporter"] = commHttpsCommPol.NodeExporter.ValueString()
			}
			if !commHttpsCommPol.Port.IsNull() && !commHttpsCommPol.Port.IsUnknown() {
				childMap.Attributes["port"] = commHttpsCommPol.Port.ValueString()
			}
			if !commHttpsCommPol.Referer.IsNull() && !commHttpsCommPol.Referer.IsUnknown() {
				childMap.Attributes["referer"] = commHttpsCommPol.Referer.ValueString()
			}
			if !commHttpsCommPol.ServerHeader.IsNull() && !commHttpsCommPol.ServerHeader.IsUnknown() {
				childMap.Attributes["serverHeader"] = commHttpsCommPol.ServerHeader.ValueString()
			}
			if !commHttpsCommPol.SslProtocols.IsNull() && !commHttpsCommPol.SslProtocols.IsUnknown() {
				var tmpSslProtocols []string
				commHttpsCommPol.SslProtocols.ElementsAs(ctx, &tmpSslProtocols, false)
				childMap.Attributes["sslProtocols"] = strings.Join(tmpSslProtocols, ",")
			}
			if !commHttpsCommPol.ThrottleRate.IsNull() && !commHttpsCommPol.ThrottleRate.IsUnknown() {
				childMap.Attributes["throttleRate"] = commHttpsCommPol.ThrottleRate.ValueString()
			}
			if !commHttpsCommPol.ThrottleSt.IsNull() && !commHttpsCommPol.ThrottleSt.IsUnknown() {
				childMap.Attributes["throttleSt"] = commHttpsCommPol.ThrottleSt.ValueString()
			}
			if !commHttpsCommPol.VisoreAccess.IsNull() && !commHttpsCommPol.VisoreAccess.IsUnknown() {
				childMap.Attributes["visoreAccess"] = commHttpsCommPol.VisoreAccess.ValueString()
			}
			var commRsClientCertCACommHttpsCommPolPlan, commRsClientCertCACommHttpsCommPolState []CommRsClientCertCACommHttpsCommPolResourceModel
			commHttpsCommPol.CommRsClientCertCA.ElementsAs(ctx, &commRsClientCertCACommHttpsCommPolPlan, false)
			for _, commHttpscommRsClientCertCAState := range commHttpsCommPolState {
				commHttpscommRsClientCertCAState.CommRsClientCertCA.ElementsAs(ctx, &commRsClientCertCACommHttpsCommPolState, false)
				if len(commRsClientCertCACommHttpsCommPolPlan) == 0 && len(commRsClientCertCACommHttpsCommPolState) == 1 {
					commRsClientCertCACommHttpsCommPolChildMap := NewAciObject()
					commRsClientCertCACommHttpsCommPolChildMap.Attributes["status"] = "deleted"
					CommHttpsCommPolChildren = append(CommHttpsCommPolChildren, map[string]interface{}{"commRsClientCertCA": commRsClientCertCACommHttpsCommPolChildMap})
				}
			}
			if !commHttpsCommPol.CommRsClientCertCA.IsNull() && !commHttpsCommPol.CommRsClientCertCA.IsUnknown() {
				for _, commRsClientCertCACommHttpsCommPol := range commRsClientCertCACommHttpsCommPolPlan {
					if !commRsClientCertCACommHttpsCommPol.Annotation.IsNull() && !commRsClientCertCACommHttpsCommPol.Annotation.IsUnknown() {
						commRsClientCertCACommHttpsCommPolChildMap.Attributes["annotation"] = commRsClientCertCACommHttpsCommPol.Annotation.ValueString()
					} else {
						commRsClientCertCACommHttpsCommPolChildMap.Attributes["annotation"] = globalAnnotation
					}
					if !commRsClientCertCACommHttpsCommPol.TDn.IsNull() && !commRsClientCertCACommHttpsCommPol.TDn.IsUnknown() {
						commRsClientCertCACommHttpsCommPolChildMap.Attributes["tDn"] = commRsClientCertCACommHttpsCommPol.TDn.ValueString()
					}
					var tagAnnotationCommRsClientCertCACommHttpsCommPolPlan, tagAnnotationCommRsClientCertCACommHttpsCommPolState []TagAnnotationCommRsClientCertCACommHttpsCommPolResourceModel
					commRsClientCertCACommHttpsCommPol.TagAnnotation.ElementsAs(ctx, &tagAnnotationCommRsClientCertCACommHttpsCommPolPlan, false)
					for _, commRsClientCertCAtagAnnotationState := range commRsClientCertCACommHttpsCommPolState {
						commRsClientCertCAtagAnnotationState.TagAnnotation.ElementsAs(ctx, &tagAnnotationCommRsClientCertCACommHttpsCommPolState, false)
						if len(tagAnnotationCommRsClientCertCACommHttpsCommPolPlan) == 0 && len(tagAnnotationCommRsClientCertCACommHttpsCommPolState) == 1 {
							tagAnnotationCommRsClientCertCACommHttpsCommPolChildMap := NewAciObject()
							tagAnnotationCommRsClientCertCACommHttpsCommPolChildMap.Attributes["status"] = "deleted"
							CommRsClientCertCACommHttpsCommPolChildren = append(CommRsClientCertCACommHttpsCommPolChildren, map[string]interface{}{"tagAnnotation": tagAnnotationCommRsClientCertCACommHttpsCommPolChildMap})
						}
					}
					if !commRsClientCertCACommHttpsCommPol.TagAnnotation.IsNull() && !commRsClientCertCACommHttpsCommPol.TagAnnotation.IsUnknown() {
						for _, tagAnnotationCommRsClientCertCACommHttpsCommPol := range tagAnnotationCommRsClientCertCACommHttpsCommPolPlan {
							if !tagAnnotationCommRsClientCertCACommHttpsCommPol.Key.IsNull() && !tagAnnotationCommRsClientCertCACommHttpsCommPol.Key.IsUnknown() {
								tagAnnotationCommRsClientCertCACommHttpsCommPolChildMap.Attributes["key"] = tagAnnotationCommRsClientCertCACommHttpsCommPol.Key.ValueString()
							}
							if !tagAnnotationCommRsClientCertCACommHttpsCommPol.Value.IsNull() && !tagAnnotationCommRsClientCertCACommHttpsCommPol.Value.IsUnknown() {
								tagAnnotationCommRsClientCertCACommHttpsCommPolChildMap.Attributes["value"] = tagAnnotationCommRsClientCertCACommHttpsCommPol.Value.ValueString()
							}
							CommRsClientCertCACommHttpsCommPolChildren = append(CommRsClientCertCACommHttpsCommPolChildren, map[string]interface{}{"tagAnnotation": tagAnnotationCommRsClientCertCACommHttpsCommPolChildMap})
						}
					}
					var tagTagCommRsClientCertCACommHttpsCommPolPlan, tagTagCommRsClientCertCACommHttpsCommPolState []TagTagCommRsClientCertCACommHttpsCommPolResourceModel
					commRsClientCertCACommHttpsCommPol.TagTag.ElementsAs(ctx, &tagTagCommRsClientCertCACommHttpsCommPolPlan, false)
					for _, commRsClientCertCAtagTagState := range commRsClientCertCACommHttpsCommPolState {
						commRsClientCertCAtagTagState.TagTag.ElementsAs(ctx, &tagTagCommRsClientCertCACommHttpsCommPolState, false)
						if len(tagTagCommRsClientCertCACommHttpsCommPolPlan) == 0 && len(tagTagCommRsClientCertCACommHttpsCommPolState) == 1 {
							tagTagCommRsClientCertCACommHttpsCommPolChildMap := NewAciObject()
							tagTagCommRsClientCertCACommHttpsCommPolChildMap.Attributes["status"] = "deleted"
							CommRsClientCertCACommHttpsCommPolChildren = append(CommRsClientCertCACommHttpsCommPolChildren, map[string]interface{}{"tagTag": tagTagCommRsClientCertCACommHttpsCommPolChildMap})
						}
					}
					if !commRsClientCertCACommHttpsCommPol.TagTag.IsNull() && !commRsClientCertCACommHttpsCommPol.TagTag.IsUnknown() {
						for _, tagTagCommRsClientCertCACommHttpsCommPol := range tagTagCommRsClientCertCACommHttpsCommPolPlan {
							if !tagTagCommRsClientCertCACommHttpsCommPol.Key.IsNull() && !tagTagCommRsClientCertCACommHttpsCommPol.Key.IsUnknown() {
								tagTagCommRsClientCertCACommHttpsCommPolChildMap.Attributes["key"] = tagTagCommRsClientCertCACommHttpsCommPol.Key.ValueString()
							}
							if !tagTagCommRsClientCertCACommHttpsCommPol.Value.IsNull() && !tagTagCommRsClientCertCACommHttpsCommPol.Value.IsUnknown() {
								tagTagCommRsClientCertCACommHttpsCommPolChildMap.Attributes["value"] = tagTagCommRsClientCertCACommHttpsCommPol.Value.ValueString()
							}
							CommRsClientCertCACommHttpsCommPolChildren = append(CommRsClientCertCACommHttpsCommPolChildren, map[string]interface{}{"tagTag": tagTagCommRsClientCertCACommHttpsCommPolChildMap})
						}
					}
					CommHttpsCommPolChildren = append(CommHttpsCommPolChildren, map[string]interface{}{"commRsClientCertCA": commRsClientCertCACommHttpsCommPolChildMap})
				}
			}
			var commRsKeyRingCommHttpsCommPolPlan, commRsKeyRingCommHttpsCommPolState []CommRsKeyRingCommHttpsCommPolResourceModel
			commHttpsCommPol.CommRsKeyRing.ElementsAs(ctx, &commRsKeyRingCommHttpsCommPolPlan, false)
			for _, commHttpscommRsKeyRingState := range commHttpsCommPolState {
				commHttpscommRsKeyRingState.CommRsKeyRing.ElementsAs(ctx, &commRsKeyRingCommHttpsCommPolState, false)
				if len(commRsKeyRingCommHttpsCommPolPlan) == 0 && len(commRsKeyRingCommHttpsCommPolState) == 1 {
					diags.AddError(
						"CommRsKeyRing object cannot be deleted",
						"deletion of child is only possible upon deletion of the parent",
					)
					return nil
				}
			}
			if !commHttpsCommPol.CommRsKeyRing.IsNull() && !commHttpsCommPol.CommRsKeyRing.IsUnknown() {
				for _, commRsKeyRingCommHttpsCommPol := range commRsKeyRingCommHttpsCommPolPlan {
					if !commRsKeyRingCommHttpsCommPol.Annotation.IsNull() && !commRsKeyRingCommHttpsCommPol.Annotation.IsUnknown() {
						commRsKeyRingCommHttpsCommPolChildMap.Attributes["annotation"] = commRsKeyRingCommHttpsCommPol.Annotation.ValueString()
					} else {
						commRsKeyRingCommHttpsCommPolChildMap.Attributes["annotation"] = globalAnnotation
					}
					if !commRsKeyRingCommHttpsCommPol.TnPkiKeyRingName.IsNull() && !commRsKeyRingCommHttpsCommPol.TnPkiKeyRingName.IsUnknown() {
						commRsKeyRingCommHttpsCommPolChildMap.Attributes["tnPkiKeyRingName"] = commRsKeyRingCommHttpsCommPol.TnPkiKeyRingName.ValueString()
					}
					var tagAnnotationCommRsKeyRingCommHttpsCommPolPlan, tagAnnotationCommRsKeyRingCommHttpsCommPolState []TagAnnotationCommRsKeyRingCommHttpsCommPolResourceModel
					commRsKeyRingCommHttpsCommPol.TagAnnotation.ElementsAs(ctx, &tagAnnotationCommRsKeyRingCommHttpsCommPolPlan, false)
					for _, commRsKeyRingtagAnnotationState := range commRsKeyRingCommHttpsCommPolState {
						commRsKeyRingtagAnnotationState.TagAnnotation.ElementsAs(ctx, &tagAnnotationCommRsKeyRingCommHttpsCommPolState, false)
						if len(tagAnnotationCommRsKeyRingCommHttpsCommPolPlan) == 0 && len(tagAnnotationCommRsKeyRingCommHttpsCommPolState) == 1 {
							tagAnnotationCommRsKeyRingCommHttpsCommPolChildMap := NewAciObject()
							tagAnnotationCommRsKeyRingCommHttpsCommPolChildMap.Attributes["status"] = "deleted"
							CommRsKeyRingCommHttpsCommPolChildren = append(CommRsKeyRingCommHttpsCommPolChildren, map[string]interface{}{"tagAnnotation": tagAnnotationCommRsKeyRingCommHttpsCommPolChildMap})
						}
					}
					if !commRsKeyRingCommHttpsCommPol.TagAnnotation.IsNull() && !commRsKeyRingCommHttpsCommPol.TagAnnotation.IsUnknown() {
						for _, tagAnnotationCommRsKeyRingCommHttpsCommPol := range tagAnnotationCommRsKeyRingCommHttpsCommPolPlan {
							if !tagAnnotationCommRsKeyRingCommHttpsCommPol.Key.IsNull() && !tagAnnotationCommRsKeyRingCommHttpsCommPol.Key.IsUnknown() {
								tagAnnotationCommRsKeyRingCommHttpsCommPolChildMap.Attributes["key"] = tagAnnotationCommRsKeyRingCommHttpsCommPol.Key.ValueString()
							}
							if !tagAnnotationCommRsKeyRingCommHttpsCommPol.Value.IsNull() && !tagAnnotationCommRsKeyRingCommHttpsCommPol.Value.IsUnknown() {
								tagAnnotationCommRsKeyRingCommHttpsCommPolChildMap.Attributes["value"] = tagAnnotationCommRsKeyRingCommHttpsCommPol.Value.ValueString()
							}
							CommRsKeyRingCommHttpsCommPolChildren = append(CommRsKeyRingCommHttpsCommPolChildren, map[string]interface{}{"tagAnnotation": tagAnnotationCommRsKeyRingCommHttpsCommPolChildMap})
						}
					}
					var tagTagCommRsKeyRingCommHttpsCommPolPlan, tagTagCommRsKeyRingCommHttpsCommPolState []TagTagCommRsKeyRingCommHttpsCommPolResourceModel
					commRsKeyRingCommHttpsCommPol.TagTag.ElementsAs(ctx, &tagTagCommRsKeyRingCommHttpsCommPolPlan, false)
					for _, commRsKeyRingtagTagState := range commRsKeyRingCommHttpsCommPolState {
						commRsKeyRingtagTagState.TagTag.ElementsAs(ctx, &tagTagCommRsKeyRingCommHttpsCommPolState, false)
						if len(tagTagCommRsKeyRingCommHttpsCommPolPlan) == 0 && len(tagTagCommRsKeyRingCommHttpsCommPolState) == 1 {
							tagTagCommRsKeyRingCommHttpsCommPolChildMap := NewAciObject()
							tagTagCommRsKeyRingCommHttpsCommPolChildMap.Attributes["status"] = "deleted"
							CommRsKeyRingCommHttpsCommPolChildren = append(CommRsKeyRingCommHttpsCommPolChildren, map[string]interface{}{"tagTag": tagTagCommRsKeyRingCommHttpsCommPolChildMap})
						}
					}
					if !commRsKeyRingCommHttpsCommPol.TagTag.IsNull() && !commRsKeyRingCommHttpsCommPol.TagTag.IsUnknown() {
						for _, tagTagCommRsKeyRingCommHttpsCommPol := range tagTagCommRsKeyRingCommHttpsCommPolPlan {
							if !tagTagCommRsKeyRingCommHttpsCommPol.Key.IsNull() && !tagTagCommRsKeyRingCommHttpsCommPol.Key.IsUnknown() {
								tagTagCommRsKeyRingCommHttpsCommPolChildMap.Attributes["key"] = tagTagCommRsKeyRingCommHttpsCommPol.Key.ValueString()
							}
							if !tagTagCommRsKeyRingCommHttpsCommPol.Value.IsNull() && !tagTagCommRsKeyRingCommHttpsCommPol.Value.IsUnknown() {
								tagTagCommRsKeyRingCommHttpsCommPolChildMap.Attributes["value"] = tagTagCommRsKeyRingCommHttpsCommPol.Value.ValueString()
							}
							CommRsKeyRingCommHttpsCommPolChildren = append(CommRsKeyRingCommHttpsCommPolChildren, map[string]interface{}{"tagTag": tagTagCommRsKeyRingCommHttpsCommPolChildMap})
						}
					}
					CommHttpsCommPolChildren = append(CommHttpsCommPolChildren, map[string]interface{}{"commRsKeyRing": commRsKeyRingCommHttpsCommPolChildMap})
				}
			}
			var tagAnnotationCommHttpsCommPolPlan, tagAnnotationCommHttpsCommPolState []TagAnnotationCommHttpsCommPolResourceModel
			commHttpsCommPol.TagAnnotation.ElementsAs(ctx, &tagAnnotationCommHttpsCommPolPlan, false)
			for _, commHttpstagAnnotationState := range commHttpsCommPolState {
				commHttpstagAnnotationState.TagAnnotation.ElementsAs(ctx, &tagAnnotationCommHttpsCommPolState, false)
				if len(tagAnnotationCommHttpsCommPolPlan) == 0 && len(tagAnnotationCommHttpsCommPolState) == 1 {
					tagAnnotationCommHttpsCommPolChildMap := NewAciObject()
					tagAnnotationCommHttpsCommPolChildMap.Attributes["status"] = "deleted"
					CommHttpsCommPolChildren = append(CommHttpsCommPolChildren, map[string]interface{}{"tagAnnotation": tagAnnotationCommHttpsCommPolChildMap})
				}
			}
			if !commHttpsCommPol.TagAnnotation.IsNull() && !commHttpsCommPol.TagAnnotation.IsUnknown() {
				for _, tagAnnotationCommHttpsCommPol := range tagAnnotationCommHttpsCommPolPlan {
					if !tagAnnotationCommHttpsCommPol.Key.IsNull() && !tagAnnotationCommHttpsCommPol.Key.IsUnknown() {
						tagAnnotationCommHttpsCommPolChildMap.Attributes["key"] = tagAnnotationCommHttpsCommPol.Key.ValueString()
					}
					if !tagAnnotationCommHttpsCommPol.Value.IsNull() && !tagAnnotationCommHttpsCommPol.Value.IsUnknown() {
						tagAnnotationCommHttpsCommPolChildMap.Attributes["value"] = tagAnnotationCommHttpsCommPol.Value.ValueString()
					}
					CommHttpsCommPolChildren = append(CommHttpsCommPolChildren, map[string]interface{}{"tagAnnotation": tagAnnotationCommHttpsCommPolChildMap})
				}
			}
			var tagTagCommHttpsCommPolPlan, tagTagCommHttpsCommPolState []TagTagCommHttpsCommPolResourceModel
			commHttpsCommPol.TagTag.ElementsAs(ctx, &tagTagCommHttpsCommPolPlan, false)
			for _, commHttpstagTagState := range commHttpsCommPolState {
				commHttpstagTagState.TagTag.ElementsAs(ctx, &tagTagCommHttpsCommPolState, false)
				if len(tagTagCommHttpsCommPolPlan) == 0 && len(tagTagCommHttpsCommPolState) == 1 {
					tagTagCommHttpsCommPolChildMap := NewAciObject()
					tagTagCommHttpsCommPolChildMap.Attributes["status"] = "deleted"
					CommHttpsCommPolChildren = append(CommHttpsCommPolChildren, map[string]interface{}{"tagTag": tagTagCommHttpsCommPolChildMap})
				}
			}
			if !commHttpsCommPol.TagTag.IsNull() && !commHttpsCommPol.TagTag.IsUnknown() {
				for _, tagTagCommHttpsCommPol := range tagTagCommHttpsCommPolPlan {
					if !tagTagCommHttpsCommPol.Key.IsNull() && !tagTagCommHttpsCommPol.Key.IsUnknown() {
						tagTagCommHttpsCommPolChildMap.Attributes["key"] = tagTagCommHttpsCommPol.Key.ValueString()
					}
					if !tagTagCommHttpsCommPol.Value.IsNull() && !tagTagCommHttpsCommPol.Value.IsUnknown() {
						tagTagCommHttpsCommPolChildMap.Attributes["value"] = tagTagCommHttpsCommPol.Value.ValueString()
					}
					CommHttpsCommPolChildren = append(CommHttpsCommPolChildren, map[string]interface{}{"tagTag": tagTagCommHttpsCommPolChildMap})
				}
			}
			childMap.Children = CommHttpsCommPolChildren
			childPayloads = append(childPayloads, map[string]interface{}{"commHttps": childMap})
		}
		if len(commHttpsCommPolPlan) == 0 && len(commHttpsCommPolState) == 1 {
			diags.AddError(
				"CommHttps object cannot be deleted",
				"deletion of child is only possible upon deletion of the parent",
			)
			return nil
		}
	} else {
		data.CommHttps = types.SetNull(data.CommHttps.ElementType(ctx))
	}

	return childPayloads
}

func getCommPolTagAnnotationChildPayloads(ctx context.Context, diags *diag.Diagnostics, data *CommPolResourceModel, tagAnnotationCommPolPlan, tagAnnotationCommPolState []TagAnnotationCommPolResourceModel) []map[string]interface{} {
	childMap := NewAciObject()
	childPayloads := []map[string]interface{}{}
	if !data.TagAnnotation.IsNull() && !data.TagAnnotation.IsUnknown() {
		tagAnnotationIdentifiers := []TagAnnotationIdentifier{}
		for _, tagAnnotationCommPol := range tagAnnotationCommPolPlan {
			if !tagAnnotationCommPol.Key.IsNull() && !tagAnnotationCommPol.Key.IsUnknown() {
				childMap.Attributes["key"] = tagAnnotationCommPol.Key.ValueString()
			}
			if !tagAnnotationCommPol.Value.IsNull() && !tagAnnotationCommPol.Value.IsUnknown() {
				childMap.Attributes["value"] = tagAnnotationCommPol.Value.ValueString()
			}
			childPayloads = append(childPayloads, map[string]interface{}{"tagAnnotation": childMap})
			tagAnnotationIdentifier := TagAnnotationIdentifier{}
			tagAnnotationIdentifier.Key = tagAnnotationCommPol.Key
			tagAnnotationIdentifiers = append(tagAnnotationIdentifiers, tagAnnotationIdentifier)
		}
		for _, tagAnnotation := range tagAnnotationCommPolState {
			delete := true
			for _, tagAnnotationIdentifier := range tagAnnotationIdentifiers {
				if tagAnnotationIdentifier.Key == tagAnnotation.Key {
					delete = false
					break
				}
			}
			if delete {
				tagAnnotationChildMapForDelete := NewAciObject()
				tagAnnotationChildMapForDelete.Attributes["status"] = "deleted"
				tagAnnotationChildMapForDelete.Attributes["key"] = tagAnnotation.Key.ValueString()
				childPayloads = append(childPayloads, map[string]interface{}{"tagAnnotation": tagAnnotationChildMapForDelete})
			}
		}
	} else {
		data.TagAnnotation = types.SetNull(data.TagAnnotation.ElementType(ctx))
	}

	return childPayloads
}

func getCommPolTagTagChildPayloads(ctx context.Context, diags *diag.Diagnostics, data *CommPolResourceModel, tagTagCommPolPlan, tagTagCommPolState []TagTagCommPolResourceModel) []map[string]interface{} {
	childMap := NewAciObject()
	childPayloads := []map[string]interface{}{}
	if !data.TagTag.IsNull() && !data.TagTag.IsUnknown() {
		tagTagIdentifiers := []TagTagIdentifier{}
		for _, tagTagCommPol := range tagTagCommPolPlan {
			if !tagTagCommPol.Key.IsNull() && !tagTagCommPol.Key.IsUnknown() {
				childMap.Attributes["key"] = tagTagCommPol.Key.ValueString()
			}
			if !tagTagCommPol.Value.IsNull() && !tagTagCommPol.Value.IsUnknown() {
				childMap.Attributes["value"] = tagTagCommPol.Value.ValueString()
			}
			childPayloads = append(childPayloads, map[string]interface{}{"tagTag": childMap})
			tagTagIdentifier := TagTagIdentifier{}
			tagTagIdentifier.Key = tagTagCommPol.Key
			tagTagIdentifiers = append(tagTagIdentifiers, tagTagIdentifier)
		}
		for _, tagTag := range tagTagCommPolState {
			delete := true
			for _, tagTagIdentifier := range tagTagIdentifiers {
				if tagTagIdentifier.Key == tagTag.Key {
					delete = false
					break
				}
			}
			if delete {
				tagTagChildMapForDelete := NewAciObject()
				tagTagChildMapForDelete.Attributes["status"] = "deleted"
				tagTagChildMapForDelete.Attributes["key"] = tagTag.Key.ValueString()
				childPayloads = append(childPayloads, map[string]interface{}{"tagTag": tagTagChildMapForDelete})
			}
		}
	} else {
		data.TagTag = types.SetNull(data.TagTag.ElementType(ctx))
	}

	return childPayloads
}

func getCommPolCreateJsonPayload(ctx context.Context, diags *diag.Diagnostics, data *CommPolResourceModel, commHttpsPlan, commHttpsState []CommHttpsCommPolResourceModel, tagAnnotationPlan, tagAnnotationState []TagAnnotationCommPolResourceModel, tagTagPlan, tagTagState []TagTagCommPolResourceModel) *container.Container {
	payloadMap := map[string]interface{}{}
	payloadMap["attributes"] = map[string]string{}
	childPayloads := []map[string]interface{}{}

	CommHttpschildPayloads := getCommPolCommHttpsChildPayloads(ctx, diags, data, commHttpsPlan, commHttpsState)
	if CommHttpschildPayloads == nil {
		return nil
	}
	childPayloads = append(childPayloads, CommHttpschildPayloads...)

	TagAnnotationchildPayloads := getCommPolTagAnnotationChildPayloads(ctx, diags, data, tagAnnotationPlan, tagAnnotationState)
	if TagAnnotationchildPayloads == nil {
		return nil
	}
	childPayloads = append(childPayloads, TagAnnotationchildPayloads...)

	TagTagchildPayloads := getCommPolTagTagChildPayloads(ctx, diags, data, tagTagPlan, tagTagState)
	if TagTagchildPayloads == nil {
		return nil
	}
	childPayloads = append(childPayloads, TagTagchildPayloads...)

	payloadMap["children"] = childPayloads
	if !data.Annotation.IsNull() && !data.Annotation.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["annotation"] = data.Annotation.ValueString()
	}
	if !data.Descr.IsNull() && !data.Descr.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["descr"] = data.Descr.ValueString()
	}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["name"] = data.Name.ValueString()
	}
	if !data.NameAlias.IsNull() && !data.NameAlias.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["nameAlias"] = data.NameAlias.ValueString()
	}
	if !data.OwnerKey.IsNull() && !data.OwnerKey.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["ownerKey"] = data.OwnerKey.ValueString()
	}
	if !data.OwnerTag.IsNull() && !data.OwnerTag.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["ownerTag"] = data.OwnerTag.ValueString()
	}
	if !data.StrictSecurityOnApicOOBSubnet.IsNull() && !data.StrictSecurityOnApicOOBSubnet.IsUnknown() {
		payloadMap["attributes"].(map[string]string)["strictSecurityOnApicOOBSubnet"] = data.StrictSecurityOnApicOOBSubnet.ValueString()
	}

	payload, err := json.Marshal(map[string]interface{}{"commPol": payloadMap})
	if err != nil {
		diags.AddError(
			"Marshalling of json payload failed",
			fmt.Sprintf("Err: %s. Please report this issue to the provider developers.", err),
		)
		return nil
	}

	jsonPayload, err := container.ParseJSON(payload)

	if err != nil {
		diags.AddError(
			"Construction of json payload failed",
			fmt.Sprintf("Err: %s. Please report this issue to the provider developers.", err),
		)
		return nil
	}
	return jsonPayload
}
